version: '3'
services:
  keycloak:
    image: jboss/keycloak:8.0.0
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Password1.
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 9999:8080