spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization-service
          uri: 'http://localhost:9999'
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/auth/realms/master/protocol/openid-connect/certs